version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building the static site..."
artifacts:
  files:
    - '**/*'
  base-directory: .
